"""Protocol every renderer must satisfy."""

from __future__ import annotations
from typing import Any, Protocol


class RendererBase(Protocol):
    def make_widget(self, input_data: Any): ...
    def update_widget(self, widget, input_data: Any, frame_states: dict) -> None: ...
    def compute_states(self, frames: list[dict], up_to: int) -> dict: ...
    def filter_frames(self, frames: list[dict]) -> list[dict]: ...
    def explain_frame(self, frame: dict, step: int, total: int) -> str: ...
    def apply_frame_extras(self, screen, frame: dict) -> None: ...
    def legend_entries(self) -> list[tuple[str, str, str]]: ...        # (color, icon, label)
    def variable_entries(self, frame: dict) -> list[tuple[str, str, str]]: ...  # (name, value, color)
    def parse_input(self, raw: str) -> Any: ...
    def serialize_input(self, input_data: Any) -> str: ...
