TOPICS = ["all", "grid", "tree", "graph", "array", "string", "dp", "sliding_window", "two_pointer", "stack", "queue", "linked_list"]
DIFFICULTIES = ["all", "easy", "medium", "hard"]

PROBLEMS = [
    {"id": "count_islands",      "title": "Count Islands",                  "topic": "grid",   "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "number_of_islands",  "title": "Number of Islands II",           "topic": "grid",   "difficulty": "hard",   "renderer": "grid",  "available": True},
    {"id": "max_area_island",    "title": "Max Area of Island",             "topic": "grid",   "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "island_perimeter",   "title": "Island Perimeter",               "topic": "grid",   "difficulty": "easy",   "renderer": "grid",  "available": True},
    {"id": "closed_island",      "title": "Closed Island",                  "topic": "grid",   "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "num_enclaves",       "title": "Number of Enclaves",             "topic": "grid",   "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "shortest_path_binary_matrix", "title": "Shortest Path in Binary Matrix", "topic": "grid", "difficulty": "medium", "renderer": "grid", "available": True},
    {"id": "update_matrix",      "title": "01 Matrix",                      "topic": "grid",   "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "shortest_bridge",    "title": "Shortest Bridge",                "topic": "grid",   "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "as_far_from_land",   "title": "As Far from Land as Possible",   "topic": "grid",   "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "unique_paths_ii",    "title": "Unique Paths II",                "topic": "grid",   "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "maximal_square",     "title": "Maximal Square",                 "topic": "grid",   "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "largest_1_bordered_square", "title": "Largest 1-Bordered Square", "topic": "grid", "difficulty": "medium", "renderer": "grid", "available": True},
    {"id": "count_square_submatrices", "title": "Count Square Submatrices", "topic": "grid",   "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "game_of_life",       "title": "Game of Life",                   "topic": "grid",   "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "making_large_island","title": "Making A Large Island",          "topic": "grid",   "difficulty": "hard",   "renderer": "grid",  "available": True},
    {"id": "count_servers",      "title": "Count Servers That Communicate", "topic": "grid",   "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "find_farmland",      "title": "Find All Groups of Farmland",    "topic": "grid",   "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "walls_and_gates",    "title": "Walls and Gates (BFS)",          "topic": "grid",   "difficulty": "medium", "renderer": "queue", "available": True},
    {"id": "rotting_oranges",    "title": "Rotting Oranges (BFS)",          "topic": "grid",   "difficulty": "medium", "renderer": "queue", "available": True},
    {"id": "bt_inorder",         "title": "Binary Tree Inorder Traversal",  "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "bt_preorder",        "title": "Binary Tree Preorder Traversal", "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "bt_postorder",       "title": "Binary Tree Postorder Traversal", "topic": "tree",  "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "bt_max_depth",       "title": "Maximum Depth of Binary Tree",   "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "bt_path_sum",        "title": "Binary Tree Path Sum",           "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "bt_level_order",     "title": "Binary Tree Level Order BFS",    "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "balanced_bt",        "title": "Balanced Binary Tree",           "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "diameter_bt",        "title": "Diameter of Binary Tree",        "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "flatten_tree",       "title": "Flatten Binary Tree to List",    "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "invert_tree",        "title": "Invert Binary Tree",             "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "kth_smallest_bst",   "title": "Kth Smallest Element in BST",    "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "lca_bst",            "title": "Lowest Common Ancestor of BST",  "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "lca_bt",             "title": "Lowest Common Ancestor of BT",   "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "max_path_sum",       "title": "Binary Tree Max Path Sum",       "topic": "tree",   "difficulty": "hard",   "renderer": "tree",  "available": True},
    {"id": "path_sum_ii",        "title": "Binary Tree Path Sum II",        "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "right_side_view",    "title": "Binary Tree Right Side View",    "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "sum_numbers",        "title": "Sum Root to Leaf Numbers",       "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "symmetric_tree",     "title": "Symmetric Tree",                 "topic": "tree",   "difficulty": "easy",   "renderer": "tree",  "available": True},
    {"id": "validate_bst",       "title": "Validate Binary Search Tree",    "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "zigzag_level_order", "title": "BT Zigzag Level Order BFS",      "topic": "tree",   "difficulty": "medium", "renderer": "tree",  "available": True},
    {"id": "two_sum",            "title": "Two Sum",                        "topic": "array",  "difficulty": "easy",   "renderer": "array", "available": True},
    {"id": "merge_intervals",    "title": "Merge Intervals",                "topic": "array",  "difficulty": "medium", "renderer": "array", "available": True},
    {"id": "valid_parens",       "title": "Valid Parentheses",              "topic": "string", "difficulty": "easy",   "renderer": "array", "available": True},
    {"id": "dijkstra",           "title": "Dijkstra Shortest Path",         "topic": "graph",  "difficulty": "medium", "renderer": "graph", "available": True},
    {"id": "bfs_graph",          "title": "Graph BFS",                      "topic": "graph",  "difficulty": "easy",   "renderer": "graph", "available": True},
    {"id": "graph_count_islands", "title": "Count Islands",                 "topic": "graph",  "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "graph_number_of_islands", "title": "Number of Islands II",      "topic": "graph",  "difficulty": "hard",   "renderer": "grid",  "available": True},
    {"id": "graph_max_area_island", "title": "Max Area of Island",          "topic": "graph",  "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "graph_island_perimeter", "title": "Island Perimeter",           "topic": "graph",  "difficulty": "easy",   "renderer": "grid",  "available": True},
    {"id": "graph_closed_island", "title": "Closed Island",                 "topic": "graph",  "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "graph_num_enclaves", "title": "Number of Enclaves",             "topic": "graph",  "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "graph_shortest_path_binary_matrix", "title": "Shortest Path in Binary Matrix", "topic": "graph", "difficulty": "medium", "renderer": "grid", "available": True},
    {"id": "graph_update_matrix", "title": "01 Matrix",                     "topic": "graph",  "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "graph_shortest_bridge", "title": "Shortest Bridge",             "topic": "graph",  "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "graph_as_far_from_land", "title": "As Far from Land as Possible", "topic": "graph", "difficulty": "medium", "renderer": "grid", "available": True},
    {"id": "graph_unique_paths_ii", "title": "Unique Paths II",             "topic": "graph",  "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "graph_game_of_life", "title": "Game of Life",                   "topic": "graph",  "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "graph_making_large_island", "title": "Making A Large Island",   "topic": "graph",  "difficulty": "hard",   "renderer": "grid",  "available": True},
    {"id": "graph_count_servers", "title": "Count Servers That Communicate","topic": "graph",  "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "graph_find_farmland", "title": "Find All Groups of Farmland",   "topic": "graph",  "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "graph_walls_and_gates", "title": "Walls and Gates (BFS)",       "topic": "graph",  "difficulty": "medium", "renderer": "queue", "available": True},
    {"id": "graph_rotting_oranges", "title": "Rotting Oranges (BFS)",       "topic": "graph",  "difficulty": "medium", "renderer": "queue", "available": True},
    {"id": "graph_maximal_square", "title": "Maximal Square",               "topic": "graph",  "difficulty": "medium", "renderer": "grid",  "available": True},
    {"id": "array_two_sum_sorted", "title": "Two Sum II - Sorted Array",    "topic": "array",  "difficulty": "medium", "renderer": "two_pointer", "available": True},
    {"id": "array_three_sum",     "title": "3Sum",                          "topic": "array",  "difficulty": "medium", "renderer": "two_pointer", "available": True},
    {"id": "array_container_water", "title": "Container With Most Water",   "topic": "array",  "difficulty": "medium", "renderer": "two_pointer", "available": True},
    {"id": "array_trapping_rain_water", "title": "Trapping Rain Water",     "topic": "array",  "difficulty": "hard",   "renderer": "two_pointer", "available": True},
    {"id": "array_sort_colors",   "title": "Sort Colors (Three Pointer)",   "topic": "array",  "difficulty": "medium", "renderer": "two_pointer", "available": True},
    {"id": "array_remove_duplicates", "title": "Remove Duplicates from Sorted", "topic": "array", "difficulty": "easy", "renderer": "two_pointer", "available": True},
    {"id": "array_move_zeroes",   "title": "Move Zeroes",                   "topic": "array",  "difficulty": "easy",   "renderer": "two_pointer", "available": True},
    {"id": "array_min_size_subarray_sum", "title": "Minimum Size Subarray Sum", "topic": "array", "difficulty": "medium", "renderer": "sliding_window", "available": True},
    {"id": "array_max_consecutive_ones_iii", "title": "Max Consecutive Ones III", "topic": "array", "difficulty": "medium", "renderer": "sliding_window", "available": True},
    {"id": "array_fruit_into_baskets", "title": "Fruit Into Baskets",       "topic": "array",  "difficulty": "medium", "renderer": "sliding_window", "available": True},
    {"id": "array_sliding_window_maximum", "title": "Sliding Window Maximum", "topic": "array", "difficulty": "hard", "renderer": "sliding_window", "available": True},
    {"id": "array_max_sliding_window_queue", "title": "Sliding Window Max (Deque)", "topic": "array", "difficulty": "hard", "renderer": "queue", "available": True},
    {"id": "array_longest_increasing_subsequence", "title": "Longest Increasing Subsequence", "topic": "array", "difficulty": "medium", "renderer": "dp", "available": True},
    {"id": "array_house_robber",  "title": "House Robber",                  "topic": "array",  "difficulty": "medium", "renderer": "dp",    "available": True},
    {"id": "array_house_robber_ii", "title": "House Robber II",             "topic": "array",  "difficulty": "medium", "renderer": "dp",    "available": True},
    {"id": "array_coin_change",   "title": "Coin Change",                   "topic": "array",  "difficulty": "medium", "renderer": "dp",    "available": True},
    {"id": "array_partition_equal_subset_sum", "title": "Partition Equal Subset Sum", "topic": "array", "difficulty": "medium", "renderer": "dp", "available": True},
    {"id": "array_target_sum",    "title": "Target Sum",                    "topic": "array",  "difficulty": "medium", "renderer": "dp",    "available": True},
    {"id": "string_valid_palindrome", "title": "Valid Palindrome",          "topic": "string", "difficulty": "easy",   "renderer": "two_pointer", "available": True},
    {"id": "string_backspace_compare", "title": "Backspace String Compare", "topic": "string", "difficulty": "easy",   "renderer": "two_pointer", "available": True},
    {"id": "string_longest_substring_no_repeat", "title": "Longest Substring No Repeat", "topic": "string", "difficulty": "medium", "renderer": "sliding_window", "available": True},
    {"id": "string_permutation_in_string", "title": "Permutation in String","topic": "string", "difficulty": "medium", "renderer": "sliding_window", "available": True},
    {"id": "string_find_all_anagrams", "title": "Find All Anagrams in String", "topic": "string", "difficulty": "medium", "renderer": "sliding_window", "available": True},
    {"id": "string_min_window_substring", "title": "Minimum Window Substring", "topic": "string", "difficulty": "hard", "renderer": "sliding_window", "available": True},
    {"id": "string_longest_repeating_char_replace", "title": "Longest Repeating Char Replace", "topic": "string", "difficulty": "medium", "renderer": "sliding_window", "available": True},
    {"id": "string_word_break",   "title": "Word Break",                     "topic": "string", "difficulty": "medium", "renderer": "dp",    "available": True},
    {"id": "string_decode_ways",  "title": "Decode Ways",                    "topic": "string", "difficulty": "medium", "renderer": "dp",    "available": True},
    {"id": "string_interleaving_string", "title": "Interleaving String",    "topic": "string", "difficulty": "medium", "renderer": "dp",    "available": True},
    {"id": "string_distinct_subsequences", "title": "Distinct Subsequences","topic": "string", "difficulty": "hard",   "renderer": "dp",    "available": True},
    {"id": "string_lcs",          "title": "Longest Common Subsequence",     "topic": "string", "difficulty": "medium", "renderer": "dp",    "available": True},
    {"id": "string_edit_distance", "title": "Edit Distance",                 "topic": "string", "difficulty": "hard",   "renderer": "dp",    "available": True},
    {"id": "string_longest_palindromic_subsequence", "title": "Longest Palindromic Subsequence", "topic": "string", "difficulty": "medium", "renderer": "dp", "available": True},
    {"id": "string_palindromic_substrings", "title": "Palindromic Substrings", "topic": "string", "difficulty": "medium", "renderer": "dp", "available": True},
    {"id": "string_first_unique_char", "title": "First Unique Char in String", "topic": "string", "difficulty": "easy", "renderer": "queue", "available": True},
    {"id": "string_generate_parentheses", "title": "Generate Parentheses",  "topic": "string", "difficulty": "medium", "renderer": "stack", "available": True},
    {"id": "string_simplify_path", "title": "Simplify Path",                "topic": "string", "difficulty": "medium", "renderer": "stack", "available": True},
    {"id": "string_basic_calculator", "title": "Basic Calculator",          "topic": "string", "difficulty": "hard",   "renderer": "stack", "available": True},
    {"id": "climbing_stairs",    "title": "Climbing Stairs",                "topic": "dp",     "difficulty": "easy",   "renderer": "dp",    "available": True},
    {"id": "min_cost_climbing_stairs", "title": "Min Cost Climbing Stairs", "topic": "dp",     "difficulty": "easy",   "renderer": "dp",    "available": True},
    {"id": "house_robber",       "title": "House Robber",                   "topic": "dp",     "difficulty": "medium", "renderer": "dp",    "available": True},
    {"id": "house_robber_ii",    "title": "House Robber II",                "topic": "dp",     "difficulty": "medium", "renderer": "dp",    "available": True},
    {"id": "coin_change",        "title": "Coin Change",                    "topic": "dp",     "difficulty": "medium", "renderer": "dp",    "available": True},
    {"id": "coin_change_ii",     "title": "Coin Change II",                 "topic": "dp",     "difficulty": "medium", "renderer": "dp",    "available": True},
    {"id": "longest_increasing_subsequence", "title": "Longest Increasing Subsequence", "topic": "dp", "difficulty": "medium", "renderer": "dp", "available": True},
    {"id": "partition_equal_subset_sum", "title": "Partition Equal Subset Sum", "topic": "dp", "difficulty": "medium", "renderer": "dp", "available": True},
    {"id": "target_sum",         "title": "Target Sum",                     "topic": "dp",     "difficulty": "medium", "renderer": "dp",    "available": True},
    {"id": "word_break",         "title": "Word Break",                     "topic": "dp",     "difficulty": "medium", "renderer": "dp",    "available": True},
    {"id": "decode_ways",        "title": "Decode Ways",                    "topic": "dp",     "difficulty": "medium", "renderer": "dp",    "available": True},
    {"id": "unique_paths",       "title": "Unique Paths",                   "topic": "dp",     "difficulty": "medium", "renderer": "dp",    "available": True},
    {"id": "min_path_sum",       "title": "Minimum Path Sum",               "topic": "dp",     "difficulty": "medium", "renderer": "dp",    "available": True},
    {"id": "triangle",           "title": "Triangle",                       "topic": "dp",     "difficulty": "medium", "renderer": "dp",    "available": True},
    {"id": "edit_distance",      "title": "Edit Distance",                  "topic": "dp",     "difficulty": "hard",   "renderer": "dp",    "available": True},
    {"id": "interleaving_string","title": "Interleaving String",            "topic": "dp",     "difficulty": "medium", "renderer": "dp",    "available": True},
    {"id": "distinct_subsequences", "title": "Distinct Subsequences",       "topic": "dp",     "difficulty": "hard",   "renderer": "dp",    "available": True},
    {"id": "longest_palindromic_subsequence", "title": "Longest Palindromic Subsequence", "topic": "dp", "difficulty": "medium", "renderer": "dp", "available": True},
    {"id": "palindromic_substrings", "title": "Palindromic Substrings",     "topic": "dp",     "difficulty": "medium", "renderer": "dp",    "available": True},
    {"id": "lcs",                "title": "Longest Common Subsequence",     "topic": "dp",     "difficulty": "medium", "renderer": "dp",    "available": True},

    # --- Sliding Window (10) ---
    {"id": "longest_substring_no_repeat", "title": "Longest Substring No Repeat", "topic": "sliding_window", "difficulty": "medium", "renderer": "sliding_window", "available": True},
    {"id": "min_size_subarray_sum",      "title": "Minimum Size Subarray Sum",     "topic": "sliding_window", "difficulty": "medium", "renderer": "sliding_window", "available": True},
    {"id": "max_consecutive_ones_iii",    "title": "Max Consecutive Ones III",     "topic": "sliding_window", "difficulty": "medium", "renderer": "sliding_window", "available": True},
    {"id": "permutation_in_string",       "title": "Permutation in String",        "topic": "sliding_window", "difficulty": "medium", "renderer": "sliding_window", "available": True},
    {"id": "find_all_anagrams",           "title": "Find All Anagrams in String",  "topic": "sliding_window", "difficulty": "medium", "renderer": "sliding_window", "available": True},
    {"id": "min_window_substring",        "title": "Minimum Window Substring",     "topic": "sliding_window", "difficulty": "hard",   "renderer": "sliding_window", "available": True},
    {"id": "longest_repeating_char_replace", "title": "Longest Repeating Char Replace", "topic": "sliding_window", "difficulty": "medium", "renderer": "sliding_window", "available": True},
    {"id": "sliding_window_maximum",      "title": "Sliding Window Maximum",       "topic": "sliding_window", "difficulty": "hard",   "renderer": "sliding_window", "available": True},
    {"id": "subarrays_k_different",       "title": "Subarrays with K Diff Ints",   "topic": "sliding_window", "difficulty": "hard",   "renderer": "sliding_window", "available": True},
    {"id": "fruit_into_baskets",          "title": "Fruit Into Baskets",           "topic": "sliding_window", "difficulty": "medium", "renderer": "sliding_window", "available": True},

    # --- Two Pointer (10) ---
    {"id": "valid_palindrome",           "title": "Valid Palindrome",              "topic": "two_pointer",    "difficulty": "easy",   "renderer": "two_pointer",    "available": True},
    {"id": "two_sum_sorted",             "title": "Two Sum II - Sorted Array",     "topic": "two_pointer",    "difficulty": "medium", "renderer": "two_pointer",    "available": True},
    {"id": "three_sum",                  "title": "3Sum",                          "topic": "two_pointer",    "difficulty": "medium", "renderer": "two_pointer",    "available": True},
    {"id": "container_water",            "title": "Container With Most Water",     "topic": "two_pointer",    "difficulty": "medium", "renderer": "two_pointer",    "available": True},
    {"id": "trapping_rain_water",        "title": "Trapping Rain Water",           "topic": "two_pointer",    "difficulty": "hard",   "renderer": "two_pointer",    "available": True},
    {"id": "sort_colors",                "title": "Sort Colors (Three Pointer)",   "topic": "two_pointer",    "difficulty": "medium", "renderer": "two_pointer",    "available": True},
    {"id": "remove_duplicates",          "title": "Remove Duplicates from Sorted", "topic": "two_pointer",    "difficulty": "easy",   "renderer": "two_pointer",    "available": True},
    {"id": "move_zeroes",                "title": "Move Zeroes",                   "topic": "two_pointer",    "difficulty": "easy",   "renderer": "two_pointer",    "available": True},
    {"id": "backspace_compare",          "title": "Backspace String Compare",      "topic": "two_pointer",    "difficulty": "easy",   "renderer": "two_pointer",    "available": True},
    {"id": "assign_cookies",             "title": "Assign Cookies",                "topic": "two_pointer",    "difficulty": "easy",   "renderer": "two_pointer",    "available": True},

    # --- Stack (10) ---
    {"id": "min_stack",                  "title": "Min Stack",                     "topic": "stack",          "difficulty": "medium", "renderer": "stack",          "available": True},
    {"id": "eval_rpn",                   "title": "Evaluate Reverse Polish Notation","topic": "stack",        "difficulty": "medium", "renderer": "stack",          "available": True},
    {"id": "generate_parentheses",       "title": "Generate Parentheses",          "topic": "stack",          "difficulty": "medium", "renderer": "stack",          "available": True},
    {"id": "daily_temperatures",         "title": "Daily Temperatures",            "topic": "stack",          "difficulty": "medium", "renderer": "stack",          "available": True},
    {"id": "next_greater_element",       "title": "Next Greater Element I",        "topic": "stack",          "difficulty": "easy",   "renderer": "stack",          "available": True},
    {"id": "simplify_path",              "title": "Simplify Path",                 "topic": "stack",          "difficulty": "medium", "renderer": "stack",          "available": True},
    {"id": "asteroid_collision",         "title": "Asteroid Collision",            "topic": "stack",          "difficulty": "medium", "renderer": "stack",          "available": True},
    {"id": "online_stock_span",          "title": "Online Stock Span",             "topic": "stack",          "difficulty": "medium", "renderer": "stack",          "available": True},
    {"id": "basic_calculator",           "title": "Basic Calculator",              "topic": "stack",          "difficulty": "hard",   "renderer": "stack",          "available": True},
    {"id": "remove_k_digits",            "title": "Remove K Digits",               "topic": "stack",          "difficulty": "medium", "renderer": "stack",          "available": True},

    # --- Queue (10) ---
    {"id": "implement_stack_queue",      "title": "Implement Stack using Queues",   "topic": "queue",          "difficulty": "easy",   "renderer": "queue",          "available": True},
    {"id": "implement_queue_stack",      "title": "Implement Queue using Stacks",   "topic": "queue",          "difficulty": "easy",   "renderer": "queue",          "available": True},
    {"id": "recent_calls",               "title": "Number of Recent Calls",        "topic": "queue",          "difficulty": "easy",   "renderer": "queue",          "available": True},
    {"id": "first_unique_char",          "title": "First Unique Char in String",   "topic": "queue",          "difficulty": "easy",   "renderer": "queue",          "available": True},
    {"id": "moving_average",             "title": "Moving Average from Stream",    "topic": "queue",          "difficulty": "easy",   "renderer": "queue",          "available": True},
    {"id": "circular_queue",             "title": "Design Circular Queue",         "topic": "queue",          "difficulty": "medium", "renderer": "queue",          "available": True},
    {"id": "task_scheduler",             "title": "Task Scheduler",                "topic": "queue",          "difficulty": "medium", "renderer": "queue",          "available": True},
    {"id": "max_sliding_window_queue",   "title": "Sliding Window Max (Deque)",    "topic": "queue",          "difficulty": "hard",   "renderer": "queue",          "available": True},

    # --- Linked List (10) ---
    {"id": "reverse_linked_list",        "title": "Reverse Linked List",           "topic": "linked_list",    "difficulty": "easy",   "renderer": "linked_list",    "available": True},
    {"id": "merge_two_lists",            "title": "Merge Two Sorted Lists",        "topic": "linked_list",    "difficulty": "easy",   "renderer": "linked_list",    "available": True},
    {"id": "linked_list_cycle",          "title": "Linked List Cycle",             "topic": "linked_list",    "difficulty": "easy",   "renderer": "linked_list",    "available": True},
    {"id": "remove_nth_from_end",        "title": "Remove Nth Node From End",      "topic": "linked_list",    "difficulty": "medium", "renderer": "linked_list",    "available": True},
    {"id": "reorder_list",               "title": "Reorder List",                  "topic": "linked_list",    "difficulty": "medium", "renderer": "linked_list",    "available": True},
    {"id": "copy_random_list",           "title": "Copy List with Random Pointer", "topic": "linked_list",    "difficulty": "medium", "renderer": "linked_list",    "available": True},
    {"id": "add_two_numbers",            "title": "Add Two Numbers",               "topic": "linked_list",    "difficulty": "medium", "renderer": "linked_list",    "available": True},
    {"id": "intersection_two_lists",     "title": "Intersection of Two Lists",     "topic": "linked_list",    "difficulty": "easy",   "renderer": "linked_list",    "available": True},
    {"id": "palindrome_linked_list",     "title": "Palindrome Linked List",        "topic": "linked_list",    "difficulty": "easy",   "renderer": "linked_list",    "available": True},
    {"id": "odd_even_list",              "title": "Odd Even Linked List",          "topic": "linked_list",    "difficulty": "medium", "renderer": "linked_list",    "available": True},
]

RENDERER_MAP = {
    "grid":           "lastcode.renderers.grid.GridRenderer",
    "tree":           "lastcode.renderers.tree.TreeRenderer",
    "array":          "lastcode.renderers.array.ArrayRenderer",
    "graph":          "lastcode.renderers.graph.GraphRenderer",
    "dp":             "lastcode.renderers.dp.DPRenderer",
    "sliding_window": "lastcode.renderers.sliding_window.SlidingWindowRenderer",
    "two_pointer":    "lastcode.renderers.two_pointer.TwoPointerRenderer",
    "stack":          "lastcode.renderers.stack.StackRenderer",
    "queue":          "lastcode.renderers.queue.QueueRenderer",
    "linked_list":    "lastcode.renderers.linked_list.LinkedListRenderer",
}

PROBLEM_MAP = {
    "count_islands": "lastcode.problems.grid.count_islands",
    "number_of_islands": "lastcode.problems.grid.number_of_islands",
    "max_area_island": "lastcode.problems.grid.max_area_island",
    "island_perimeter": "lastcode.problems.grid.island_perimeter",
    "closed_island": "lastcode.problems.grid.closed_island",
    "num_enclaves": "lastcode.problems.grid.num_enclaves",
    "shortest_path_binary_matrix": "lastcode.problems.grid.shortest_path_binary_matrix",
    "update_matrix": "lastcode.problems.grid.update_matrix",
    "shortest_bridge": "lastcode.problems.grid.shortest_bridge",
    "as_far_from_land": "lastcode.problems.grid.as_far_from_land",
    "unique_paths_ii": "lastcode.problems.grid.unique_paths_ii",
    "maximal_square": "lastcode.problems.grid.maximal_square",
    "largest_1_bordered_square": "lastcode.problems.grid.largest_1_bordered_square",
    "count_square_submatrices": "lastcode.problems.grid.count_square_submatrices",
    "game_of_life": "lastcode.problems.grid.game_of_life",
    "making_large_island": "lastcode.problems.grid.making_large_island",
    "count_servers": "lastcode.problems.grid.count_servers",
    "find_farmland": "lastcode.problems.grid.find_farmland",
    "bt_inorder": "lastcode.problems.tree.bt_inorder",
    "bt_preorder": "lastcode.problems.tree.bt_preorder",
    "bt_postorder": "lastcode.problems.tree.bt_postorder",
    "bt_max_depth": "lastcode.problems.tree.bt_max_depth",
    "bt_path_sum": "lastcode.problems.tree.bt_path_sum",
    "bt_level_order": "lastcode.problems.tree.bt_level_order",
    "balanced_bt": "lastcode.problems.tree.balanced_bt",
    "diameter_bt": "lastcode.problems.tree.diameter_bt",
    "flatten_tree": "lastcode.problems.tree.flatten_tree",
    "invert_tree": "lastcode.problems.tree.invert_tree",
    "kth_smallest_bst": "lastcode.problems.tree.kth_smallest_bst",
    "lca_bst": "lastcode.problems.tree.lca_bst",
    "lca_bt": "lastcode.problems.tree.lca_bt",
    "max_path_sum": "lastcode.problems.tree.max_path_sum",
    "path_sum_ii": "lastcode.problems.tree.path_sum_ii",
    "right_side_view": "lastcode.problems.tree.right_side_view",
    "sum_numbers": "lastcode.problems.tree.sum_numbers",
    "symmetric_tree": "lastcode.problems.tree.symmetric_tree",
    "validate_bst": "lastcode.problems.tree.validate_bst",
    "zigzag_level_order": "lastcode.problems.tree.zigzag_level_order",
    "two_sum": "lastcode.problems.array.two_sum",
    "merge_intervals": "lastcode.problems.array.merge_intervals",
    "valid_parens": "lastcode.problems.string.valid_parens",
    "dijkstra": "lastcode.problems.graph.dijkstra",
    "bfs_graph": "lastcode.problems.graph.bfs_graph",
    "graph_count_islands": "lastcode.problems.graph.count_islands",
    "graph_number_of_islands": "lastcode.problems.graph.number_of_islands",
    "graph_max_area_island": "lastcode.problems.graph.max_area_island",
    "graph_island_perimeter": "lastcode.problems.graph.island_perimeter",
    "graph_closed_island": "lastcode.problems.graph.closed_island",
    "graph_num_enclaves": "lastcode.problems.graph.num_enclaves",
    "graph_shortest_path_binary_matrix": "lastcode.problems.graph.shortest_path_binary_matrix",
    "graph_update_matrix": "lastcode.problems.graph.update_matrix",
    "graph_shortest_bridge": "lastcode.problems.graph.shortest_bridge",
    "graph_as_far_from_land": "lastcode.problems.graph.as_far_from_land",
    "graph_unique_paths_ii": "lastcode.problems.graph.unique_paths_ii",
    "graph_game_of_life": "lastcode.problems.graph.game_of_life",
    "graph_making_large_island": "lastcode.problems.graph.making_large_island",
    "graph_count_servers": "lastcode.problems.graph.count_servers",
    "graph_find_farmland": "lastcode.problems.graph.find_farmland",
    "graph_walls_and_gates": "lastcode.problems.graph.walls_and_gates",
    "graph_rotting_oranges": "lastcode.problems.graph.rotting_oranges",
    "graph_maximal_square": "lastcode.problems.graph.maximal_square",
    "array_two_sum_sorted": "lastcode.problems.array.two_sum_sorted",
    "array_three_sum": "lastcode.problems.array.three_sum",
    "array_container_water": "lastcode.problems.array.container_water",
    "array_trapping_rain_water": "lastcode.problems.array.trapping_rain_water",
    "array_sort_colors": "lastcode.problems.array.sort_colors",
    "array_remove_duplicates": "lastcode.problems.array.remove_duplicates",
    "array_move_zeroes": "lastcode.problems.array.move_zeroes",
    "array_min_size_subarray_sum": "lastcode.problems.array.min_size_subarray_sum",
    "array_max_consecutive_ones_iii": "lastcode.problems.array.max_consecutive_ones_iii",
    "array_fruit_into_baskets": "lastcode.problems.array.fruit_into_baskets",
    "array_sliding_window_maximum": "lastcode.problems.array.sliding_window_maximum",
    "array_max_sliding_window_queue": "lastcode.problems.array.max_sliding_window_queue",
    "array_longest_increasing_subsequence": "lastcode.problems.array.longest_increasing_subsequence",
    "array_house_robber": "lastcode.problems.array.house_robber",
    "array_house_robber_ii": "lastcode.problems.array.house_robber_ii",
    "array_coin_change": "lastcode.problems.array.coin_change",
    "array_partition_equal_subset_sum": "lastcode.problems.array.partition_equal_subset_sum",
    "array_target_sum": "lastcode.problems.array.target_sum",
    "string_valid_palindrome": "lastcode.problems.string.valid_palindrome",
    "string_backspace_compare": "lastcode.problems.string.backspace_compare",
    "string_longest_substring_no_repeat": "lastcode.problems.string.longest_substring_no_repeat",
    "string_permutation_in_string": "lastcode.problems.string.permutation_in_string",
    "string_find_all_anagrams": "lastcode.problems.string.find_all_anagrams",
    "string_min_window_substring": "lastcode.problems.string.min_window_substring",
    "string_longest_repeating_char_replace": "lastcode.problems.string.longest_repeating_char_replace",
    "string_word_break": "lastcode.problems.string.word_break",
    "string_decode_ways": "lastcode.problems.string.decode_ways",
    "string_interleaving_string": "lastcode.problems.string.interleaving_string",
    "string_distinct_subsequences": "lastcode.problems.string.distinct_subsequences",
    "string_lcs": "lastcode.problems.string.lcs",
    "string_edit_distance": "lastcode.problems.string.edit_distance",
    "string_longest_palindromic_subsequence": "lastcode.problems.string.longest_palindromic_subsequence",
    "string_palindromic_substrings": "lastcode.problems.string.palindromic_substrings",
    "string_first_unique_char": "lastcode.problems.string.first_unique_char",
    "string_generate_parentheses": "lastcode.problems.string.generate_parentheses",
    "string_simplify_path": "lastcode.problems.string.simplify_path",
    "string_basic_calculator": "lastcode.problems.string.basic_calculator",
    "climbing_stairs": "lastcode.problems.dp.climbing_stairs",
    "min_cost_climbing_stairs": "lastcode.problems.dp.min_cost_climbing_stairs",
    "house_robber": "lastcode.problems.dp.house_robber",
    "house_robber_ii": "lastcode.problems.dp.house_robber_ii",
    "coin_change": "lastcode.problems.dp.coin_change",
    "coin_change_ii": "lastcode.problems.dp.coin_change_ii",
    "longest_increasing_subsequence": "lastcode.problems.dp.longest_increasing_subsequence",
    "partition_equal_subset_sum": "lastcode.problems.dp.partition_equal_subset_sum",
    "target_sum": "lastcode.problems.dp.target_sum",
    "word_break": "lastcode.problems.dp.word_break",
    "decode_ways": "lastcode.problems.dp.decode_ways",
    "unique_paths": "lastcode.problems.dp.unique_paths",
    "min_path_sum": "lastcode.problems.dp.min_path_sum",
    "triangle": "lastcode.problems.dp.triangle",
    "edit_distance": "lastcode.problems.dp.edit_distance",
    "interleaving_string": "lastcode.problems.dp.interleaving_string",
    "distinct_subsequences": "lastcode.problems.dp.distinct_subsequences",
    "longest_palindromic_subsequence": "lastcode.problems.dp.longest_palindromic_subsequence",
    "palindromic_substrings": "lastcode.problems.dp.palindromic_substrings",
    "lcs": "lastcode.problems.dp.lcs",
    "longest_substring_no_repeat": "lastcode.problems.sliding_window.longest_substring_no_repeat",
    "min_size_subarray_sum": "lastcode.problems.sliding_window.min_size_subarray_sum",
    "max_consecutive_ones_iii": "lastcode.problems.sliding_window.max_consecutive_ones_iii",
    "permutation_in_string": "lastcode.problems.sliding_window.permutation_in_string",
    "find_all_anagrams": "lastcode.problems.sliding_window.find_all_anagrams",
    "min_window_substring": "lastcode.problems.sliding_window.min_window_substring",
    "longest_repeating_char_replace": "lastcode.problems.sliding_window.longest_repeating_char_replace",
    "sliding_window_maximum": "lastcode.problems.sliding_window.sliding_window_maximum",
    "subarrays_k_different": "lastcode.problems.sliding_window.subarrays_k_different",
    "fruit_into_baskets": "lastcode.problems.sliding_window.fruit_into_baskets",
    "valid_palindrome": "lastcode.problems.two_pointer.valid_palindrome",
    "two_sum_sorted": "lastcode.problems.two_pointer.two_sum_sorted",
    "three_sum": "lastcode.problems.two_pointer.three_sum",
    "container_water": "lastcode.problems.two_pointer.container_water",
    "trapping_rain_water": "lastcode.problems.two_pointer.trapping_rain_water",
    "sort_colors": "lastcode.problems.two_pointer.sort_colors",
    "remove_duplicates": "lastcode.problems.two_pointer.remove_duplicates",
    "move_zeroes": "lastcode.problems.two_pointer.move_zeroes",
    "backspace_compare": "lastcode.problems.two_pointer.backspace_compare",
    "assign_cookies": "lastcode.problems.two_pointer.assign_cookies",
    "min_stack": "lastcode.problems.stack.min_stack",
    "eval_rpn": "lastcode.problems.stack.eval_rpn",
    "generate_parentheses": "lastcode.problems.stack.generate_parentheses",
    "daily_temperatures": "lastcode.problems.stack.daily_temperatures",
    "next_greater_element": "lastcode.problems.stack.next_greater_element",
    "simplify_path": "lastcode.problems.stack.simplify_path",
    "asteroid_collision": "lastcode.problems.stack.asteroid_collision",
    "online_stock_span": "lastcode.problems.stack.online_stock_span",
    "basic_calculator": "lastcode.problems.stack.basic_calculator",
    "remove_k_digits": "lastcode.problems.stack.remove_k_digits",
    "implement_stack_queue": "lastcode.problems.queue.implement_stack_queue",
    "implement_queue_stack": "lastcode.problems.queue.implement_queue_stack",
    "recent_calls": "lastcode.problems.queue.recent_calls",
    "first_unique_char": "lastcode.problems.queue.first_unique_char",
    "moving_average": "lastcode.problems.queue.moving_average",
    "circular_queue": "lastcode.problems.queue.circular_queue",
    "task_scheduler": "lastcode.problems.queue.task_scheduler",
    "max_sliding_window_queue": "lastcode.problems.queue.max_sliding_window_queue",
    "walls_and_gates": "lastcode.problems.queue.walls_and_gates",
    "rotting_oranges": "lastcode.problems.queue.rotting_oranges",
    "reverse_linked_list": "lastcode.problems.linked_list.reverse_linked_list",
    "merge_two_lists": "lastcode.problems.linked_list.merge_two_lists",
    "linked_list_cycle": "lastcode.problems.linked_list.linked_list_cycle",
    "remove_nth_from_end": "lastcode.problems.linked_list.remove_nth_from_end",
    "reorder_list": "lastcode.problems.linked_list.reorder_list",
    "copy_random_list": "lastcode.problems.linked_list.copy_random_list",
    "add_two_numbers": "lastcode.problems.linked_list.add_two_numbers",
    "intersection_two_lists": "lastcode.problems.linked_list.intersection_two_lists",
    "palindrome_linked_list": "lastcode.problems.linked_list.palindrome_linked_list",
    "odd_even_list": "lastcode.problems.linked_list.odd_even_list",
}
